version: "3.7"
# docker-compose up -d --build
# docker-compose down
# to delete all databases
# docker run -it --privileged --pid=host debian nsenter -t 1 -m -u -i sh
#  >rm -r /var/lib/docker/volumes/nrstudio_orientdb_data/_data/databases/
services:
  nrstudio:
    image: nrstudio
    build: ../../application
    volumes:
      - orientdb_data:/opt/nrstudio/orientdb
      - ./logs:/opt/nrstudio/logs
    env_file: env.properties
    ports:
      - 8090:8090
      - 2480:2480
      - 2222:2222
volumes:
  orientdb_data:

