version: "3.7"
# docker-compose -f runtime/nrstudio/docker-compose.yml up -d --build
# docker-compose -f runtime/nrstudio/docker-compose.yml stop
# docker-compose -f runtime/nrstudio/docker-compose.yml start
# !!!do not down without stop, this may lead to db crash!!!
# docker-compose -f runtime/nrstudio/docker-compose.yml down
# to delete all databases
# docker run -it --rm --privileged --pid=host debian nsenter -t 1 -m -u -i sh
#  >rm -r /var/lib/docker/volumes/nrstudio_orientdb_data/_data/databases/
services:
  nrstudio:
    image: nrstudio
    build: ../../application
    volumes:
      - orientdb_data:/opt/nrstudio/orientdb
      - ./logs:/opt/nrstudio/logs
      - ./gitdb:/opt/nrstudio/gitdb
    env_file: env.properties
    ports:
      - 8090:8090
      - 2480:2480
      - 2222:2222
volumes:
  orientdb_data:

